### ISSUE TITLE
About CUSTOM dataset

### ISSUE THREAD

**Issue by yc-cui** [kwonminki/Asyrp_official#1]
It's an excellent job. I really appreciate it. 
I observed when getting LPIPS distance, it has a denoising step which makes use of pre-trained diffusion models.
If my data domain makes a great difference from the pre-trained dataset, should I pretrain the diffusion model on my dataset first?

**Comment by kwonminki** [comment]
Yes, you need a pre-trained model for that domain to effectively edit the generated image. (the model has to be able to create that image domain.)

But you don't have to measure the LPIPS distance simply to test whether it works in a specific other domain.
You can use the "--user_defined_t_edit #" and "--user_defined_t_addnoise #" options to tweak the image generation without measuring the LPIPS distance.
A recommended range for "--user_defined_t_edit #" is 400 to 700 and for "--user_defined_t_addnoise #" is 100 to 400.

**Comment by yc-cui** [comment]
OK. Thanks for your kind advice. I will have a try.
