### ISSUE TITLE
Custom Dataset training

### ISSUE THREAD

**Issue by Junhyuk93** [kwonminki/Asyrp_official#4]
Hello,

Thanks for your awesome work!

I have a question to ask the author, is it possible to learn by including attribute values and images that do not exist in the pretrained model in custom data? (ex. Can I put new Food image and Food attribute values in CelebHQ pretrained model?)

Looking forward for your reply, Thank you!

**Comment by kwonminki** [comment]
No, it's unlikely to work. You cannot apply food images to the CelebA-HQ model. (maybe) \
The generative model needs to have the ability to generate outputs similar to what you want.

However, CLIP has a strong capability for editing out-of-domain information, so it might be worth trying.

If you want to work with food data, consider using a pre-trained ImageNet model.

Check #1 

Thank you.

**Comment by Junhyuk93** [comment]
Thank you for answer!

In terms of performance, I think using ImageNet pretrained means that it is excellent,
but does that mean there is no problem with learning itself?

**Comment by dongxuyue** [comment]
> Thank you for answer!
> 
> In terms of performance, I think using ImageNet pretrained means that it is excellent, but does that mean there is no problem with learning itself?

I think that you can try to train your own diffusion model first, then you can make good use of this project.

**Comment by Junhyuk93** [comment]
That made perfect sense. thank you :)
